# Generated by Django 2.2.7 on 2019-11-15 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['descripcion'], 'verbose_name': 'Album', 'verbose_name_plural': 'Albumnes'},
        ),
        migrations.AlterModelOptions(
            name='artista',
            options={'ordering': ['nombre'], 'verbose_name': 'Artista', 'verbose_name_plural': 'Artistas'},
        ),
        migrations.AlterModelOptions(
            name='cancion',
            options={'ordering': ['nombre'], 'verbose_name': 'Cancion', 'verbose_name_plural': 'Canciones'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['descripcion'], 'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterModelOptions(
            name='idioma',
            options={'ordering': ['descripcion'], 'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
        migrations.AlterModelOptions(
            name='listareproduccion',
            options={'ordering': ['descripcion'], 'verbose_name': 'ListaReproduccion', 'verbose_name_plural': 'ListaReproduccion'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['apellidos'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
