# Generated by Django 2.2.7 on 2019-11-15 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191114_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listareproduccion',
            options={'ordering': ['descripcion'], 'verbose_name': 'Lista de Reproduccion', 'verbose_name_plural': 'Listas de Reproducciones'},
        ),
    ]
