# Generated by Django 2.2.7 on 2019-11-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191116_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Idioma',
        ),
    ]
