# Generated by Django 2.2.7 on 2019-11-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='generos',
            field=models.ManyToManyField(related_name='lista_generos', to='api.Genero'),
        ),
        migrations.AlterField(
            model_name='listareproduccion',
            name='canciones',
            field=models.ManyToManyField(related_name='lista_canciones', to='api.Cancion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
